export const DIALOGS_SET_ITEMS = "DIALOGS_SET_ITEMS";
export const DIALOGS_SET_PARTNER = "DIALOGS_SET_PARTNER";
export const DIALOGS_SET_CURRENT_DIALOG = "DIALOGS_SET_CURRENT_DIALOG";
export const DIALOGS_SET_LOADING = "DIALOGS_SET_LOADING";
export const DIALOGS_LAST_MESSAGE_READED_STATUS =
  "DIALOGS_LAST_MESSAGE_READED_STATUS";
